Adding setpythondirs so we find the right python. 	modified:   BASEFUNCS
Now correctly names BASEFUNCS since we use it here now.
Now debuglink is skipped on big-endian. The crc32
won't match little-endian crc
	modified:   DWARFTEST.sh

Using filterpathto.py to keep only the meaningful
part of the crc32.debug path.

Updated with the filtertopath path output prefix of xxx
	modified:   debuglink/baselink

	modified:   debuglink/runtest.sh
	modified:   dwarfdump-x86_64-ubuntu.O
	modified:   frame1/runtest.sh
	modified:   hughes2/runtest.sh
	modified:   testoffdie/runtest.sh

diff --git a/BASEFUNCS b/BASEFUNCS
--- a/BASEFUNCS
+++ b/BASEFUNCS
@@ -24,3 +24,23 @@ unifyddname () {
   sed -e 'sx\..*\/dwarfdumpxdwarfdumpx' < $t1 >$nend
   rm -f $t1
 }
+
+setpythondirs() {
+  p3=`which python3`
+  if [ $? -eq 0 ]
+  then
+    mypydir=python3
+    mypycom=$p3
+  else
+    p2=`which python2`
+    if [ $? -eq 0 ]
+    then
+      mypydir=python2
+      mypycom=$p2
+    else
+      echo "Cannot find python2 or python3"
+      echo "give up"
+      exit 1
+    fi
+  fi
+}
