Small changes to reflect the new expression operator presentation. 	modified:   DWARFTEST.sh
Now checking so if there is a build failure it does not just keep going.
	modified:   PICKUPBIN

Noted a requirement (tiny) that has long been present:
Put the standard dwarfdump.conf as $HOME/dwarfdump.conf
	modified:   README.txt

diff --git a/PICKUPBIN b/PICKUPBIN
--- a/PICKUPBIN
+++ b/PICKUPBIN
@@ -88,16 +88,27 @@ fi
 cd $top_build 
 echo "PICKUPBIN configure --disable-libelf for dwarfdumpnl"
 set -x
-$libdw/configure $sanitize  --disable-libelf ; make
+$libdw/configure $sanitize  --disable-libelf 
+make
+if [ $? -ne 0 ]
+then
+  echo "PICKUPBIN for dwarfdumpnl FAIL"
+  exit 1
+fi
 set +x
 cp dwarfdump/dwarfdump $targetdir/dwarfdumpnl
 
 rm -rf $top_build/*
 cd $top_build 
 set -x
-$libdw/configure $sanitize $libelfopt  --enable-oldframecol ;  make
+$libdw/configure $sanitize $libelfopt  --enable-oldframecol 
+make
+if [ $? -ne 0 ]
+then
+  echo "PICKUPBIN for oldframecol FAIL"
+  exit 1
+fi
 set +x
-
 cp libdwarf/.libs/libdwarf.a $targetdir/libdwoldframecol.a
 if [ $? -ne 0 ]
 then
@@ -108,7 +119,13 @@ fi
 rm -rf $top_build/*
 echo "PICKUPBIN configure $libelfop for --enable-windowspath"
 set -x
-$libdw/configure $sanitize $libelfopt --enable-windowspath ; make 
+$libdw/configure $sanitize $libelfopt --enable-windowspath 
+make 
+if [ $? -ne 0 ]
+then
+  echo "PICKUPBIN for --enable-windowspath  FAIL"
+  exit 1
+fi
 set +x
 
 cp dwarfdump/dwarfdump   $targetdir/dwarfdumpW
@@ -124,12 +141,24 @@ if [ $withlibelf = "withlibelf" ]
 then
   echo "PICKUPBIN configure --enable-dwarfgen --enable-dwarfexample"
   set -x
-  $libdw/configure $sanitize --enable-dwarfgen --enable-dwarfexample ;  make 
+  $libdw/configure $sanitize --enable-dwarfgen --enable-dwarfexample 
+  make 
+  if [ $? -ne 0 ]
+  then
+    echo "PICKUPBIN for withlibelf --enable-dwarfgen --enable-dwarfexample FAIL"
+    exit 1;
+  fi
   set +x
 else
   echo "PICKUPBIN configure --diable-libelf --enable-dwarfexample"
   set -x
-  $libdw/configure $sanitize --disable-libelf --enable-dwarfexample ;  make 
+  $libdw/configure $sanitize --disable-libelf --enable-dwarfexample 
+  make 
+  if [ $? -ne 0 ]
+  then
+    echo "PICKUPBIN for nolibelf --enable-dwarfgen --enable-dwarfexample FAIL"
+    exit 1;
+  fi
   set +x
 fi
 if [ $? -ne 0 ]
@@ -171,3 +200,4 @@ then
   echo "No simplereader to copy! giving up."
   exit 1;
 fi
+exit 0
